In [1]:
import pandas as pd
df = df = pd.read_csv('E:\GitHub\solar\data\Plant_1_Generation_Data.csv')
df.describe()

        PLANT_ID      DC_POWER      AC_POWER   DAILY_YIELD   TOTAL_YIELD
count    68778.0  68778.000000  68778.000000  68778.000000  6.877800e+04
mean   4135001.0   3147.426211    307.802752   3295.968737  6.978712e+06
std          0.0   4036.457169    394.396439   3145.178309  4.162720e+05
min    4135001.0      0.000000      0.000000      0.000000  6.183645e+06
25%    4135001.0      0.000000      0.000000      0.000000  6.512003e+06
50%    4135001.0    429.000000     41.493750   2658.714286  7.146685e+06
75%    4135001.0   6366.964286    623.618750   6274.000000  7.268706e+06
max    4135001.0  14471.125000   1410.950000   9163.000000  7.846821e+06

In [2]:
df.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0

In [3]:
df2 = pd.read_csv('E:\GitHub\solar\data\Plant_1_Weather_Sensor_Data.csv')
df2.describe()

        PLANT_ID  AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION
count     3182.0          3182.000000         3182.000000  3182.000000
mean   4135001.0            25.531606           31.091015     0.228313
std          0.0             3.354856           12.261222     0.300836
min    4135001.0            20.398505           18.140415     0.000000
25%    4135001.0            22.705182           21.090553     0.000000
50%    4135001.0            24.613814           24.618060     0.024653
75%    4135001.0            27.920532           41.307840     0.449588
max    4135001.0            35.252486           65.545714     1.221652

In [4]:
df2.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

In [5]:
df.shape

(68778, 7)

In [6]:
df2.shape

(3182, 6)

In [7]:
from datetime import datetime, timedelta
df2['Datetime'] = pd.to_datetime(df2['DATE_TIME'])
from datetime import datetime, timedelta
df['Datetime'] = pd.to_datetime(df['DATE_TIME'])

In [8]:
df2['Datetime']

0      2020-05-15 00:00:00
1      2020-05-15 00:15:00
2      2020-05-15 00:30:00
3      2020-05-15 00:45:00
4      2020-05-15 01:00:00
               ...
3177   2020-06-17 22:45:00
3178   2020-06-17 23:00:00
3179   2020-06-17 23:15:00
3180   2020-06-17 23:30:00
3181   2020-06-17 23:45:00
Name: Datetime, Length: 3182, dtype: datetime64[ns]

In [9]:
df2["Datetime"].map(pd.Timestamp.date).unique()

array([datetime.date(2020, 5, 15), datetime.date(2020, 5, 16),
       datetime.date(2020, 5, 17), datetime.date(2020, 5, 18),
       datetime.date(2020, 5, 19), datetime.date(2020, 5, 20),
       datetime.date(2020, 5, 21), datetime.date(2020, 5, 22),
       datetime.date(2020, 5, 23), datetime.date(2020, 5, 24),
       datetime.date(2020, 5, 25), datetime.date(2020, 5, 26),
       datetime.date(2020, 5, 27), datetime.date(2020, 5, 28),
       datetime.date(2020, 5, 29), datetime.date(2020, 5, 30),
       datetime.date(2020, 5, 31), datetime.date(2020, 6, 1),
       datetime.date(2020, 6, 2), datetime.date(2020, 6, 3),
       datetime.date(2020, 6, 4), datetime.date(2020, 6, 5),
       datetime.date(2020, 6, 6), datetime.date(2020, 6, 7),
       datetime.date(2020, 6, 8), datetime.date(2020, 6, 9),
       datetime.date(2020, 6, 10), datetime.date(2020, 6, 11),
       datetime.date(2020, 6, 12), datetime.date(2020, 6, 13),
       datetime.date(2020, 6, 14), datetime.date(2020, 6, 15),
       datetime.date(2020, 6, 16), datetime.date(2020, 6, 17)],
      dtype=object)

In [10]:
df2["Datetime"].map(pd.Timestamp.date).unique()
df['TOTAL_YIELD'][0]

6259559.0

In [11]:
import collections, numpy
collections.Counter(df2["Datetime"])

Counter({Timestamp('2020-05-15 00:00:00'): 1,
         Timestamp('2020-05-15 00:15:00'): 1,
         Timestamp('2020-05-15 00:30:00'): 1,
         Timestamp('2020-05-15 00:45:00'): 1,
         Timestamp('2020-05-15 01:00:00'): 1,
         Timestamp('2020-05-15 01:15:00'): 1,
         Timestamp('2020-05-15 01:30:00'): 1,
         Timestamp('2020-05-15 01:45:00'): 1,
         Timestamp('2020-05-15 02:00:00'): 1,
         Timestamp('2020-05-15 02:15:00'): 1,
         Timestamp('2020-05-15 02:30:00'): 1,
         Timestamp('2020-05-15 02:45:00'): 1,
         Timestamp('2020-05-15 03:00:00'): 1,
         Timestamp('2020-05-15 03:15:00'): 1,
         Timestamp('2020-05-15 03:30:00'): 1,
         Timestamp('2020-05-15 03:45:00'): 1,
         Timestamp('2020-05-15 04:00:00'): 1,
         Timestamp('2020-05-15 04:15:00'): 1,
         Timestamp('2020-05-15 04:30:00'): 1,
         Timestamp('2020-05-15 04:45:00'): 1,
         Timestamp('2020-05-15 05:00:00'): 1,
         Timestamp('2020-05-15 05:15:00'): 1,
         Timestamp('2020-05-15 05:30:00'): 1,
         Timestamp('2020-05-15 05:45:00'): 1,
         Timestamp('2020-05-15 06:00:00'): 1,
         Timestamp('2020-05-15 06:15:00'): 1,
         Timestamp('2020-05-15 06:30:00'): 1,
         Timestamp('2020-05-15 06:45:00'): 1,
         Timestamp('2020-05-15 07:00:00'): 1,
         Timestamp('2020-05-15 07:15:00'): 1,
         Timestamp('2020-05-15 07:30:00'): 1,
         Timestamp('2020-05-15 07:45:00'): 1,
         Timestamp('2020-05-15 08:00:00'): 1,
         Timestamp('2020-05-15 08:15:00'): 1,
         Timestamp('2020-05-15 08:30:00'): 1,
         Timestamp('2020-05-15 08:45:00'): 1,
         Timestamp('2020-05-15 09:00:00'): 1,
         Timestamp('2020-05-15 09:15:00'): 1,
         Timestamp('2020-05-15 09:30:00'): 1,
         Timestamp('2020-05-15 09:45:00'): 1,
         Timestamp('2020-05-15 10:00:00'): 1,
         Timestamp('2020-05-15 10:15:00'): 1,
         Timestamp('2020-05-15 10:30:00'): 1,
         Timestamp('2020-05-15 10:45:00'): 1,
         Timestamp('2020-05-15 11:00:00'): 1,
         Timestamp('2020-05-15 11:15:00'): 1,
         Timestamp('2020-05-15 11:30:00'): 1,
         Timestamp('2020-05-15 11:45:00'): 1,
         Timestamp('2020-05-15 12:00:00'): 1,
         Timestamp('2020-05-15 12:15:00'): 1,
         Timestamp('2020-05-15 12:30:00'): 1,
         Timestamp('2020-05-15 12:45:00'): 1,
         Timestamp('2020-05-15 13:00:00'): 1,
         Timestamp('2020-05-15 13:15:00'): 1,
         Timestamp('2020-05-15 13:30:00'): 1,
         Timestamp('2020-05-15 13:45:00'): 1,
         Timestamp('2020-05-15 14:00:00'): 1,
         Timestamp('2020-05-15 14:15:00'): 1,
         Timestamp('2020-05-15 14:30:00'): 1,
         Timestamp('2020-05-15 14:45:00'): 1,
         Timestamp('2020-05-15 15:00:00'): 1,
         Timestamp('2020-05-15 15:15:00'): 1,
         Timestamp('2020-05-15 15:30:00'): 1,
         Timestamp('2020-05-15 15:45:00'): 1,
         Timestamp('2020-05-15 16:00:00'): 1,
         Timestamp('2020-05-15 16:15:00'): 1,
         Timestamp('2020-05-15 16:30:00'): 1,
         Timestamp('2020-05-15 16:45:00'): 1,
         Timestamp('2020-05-15 17:00:00'): 1,
         Timestamp('2020-05-15 17:15:00'): 1,
         Timestamp('2020-05-15 17:30:00'): 1,
         Timestamp('2020-05-15 17:45:00'): 1,
         Timestamp('2020-05-15 18:00:00'): 1,
         Timestamp('2020-05-15 18:15:00'): 1,
         Timestamp('2020-05-15 18:30:00'): 1,
         Timestamp('2020-05-15 18:45:00'): 1,
         Timestamp('2020-05-15 19:00:00'): 1,
         Timestamp('2020-05-15 19:15:00'): 1,
         Timestamp('2020-05-15 19:30:00'): 1,
         Timestamp('2020-05-15 19:45:00'): 1,
         Timestamp('2020-05-15 20:00:00'): 1,
         Timestamp('2020-05-15 20:15:00'): 1,
         Timestamp('2020-05-15 20:30:00'): 1,
         Timestamp('2020-05-15 20:45:00'): 1,
         Timestamp('2020-05-15 21:00:00'): 1,
         Timestamp('2020-05-15 21:15:00'): 1,
         Timestamp('2020-05-15 21:30:00'): 1,
         Timestamp('2020-05-15 21:45:00'): 1,
         Timestamp('2020-05-15 22:00:00'): 1,
         Timestamp('2020-05-15 22:15:00'): 1,
         Timestamp('2020-05-15 22:30:00'): 1,
         Timestamp('2020-05-15 22:45:00'): 1,
         Timestamp('2020-05-15 23:00:00'): 1,
         Timestamp('2020-05-16 02:00:00'): 1,
         Timestamp('2020-05-16 02:15:00'): 1,
         Timestamp('2020-05-16 02:30:00'): 1,
         Timestamp('2020-05-16 02:45:00'): 1,
         Timestamp('2020-05-16 03:00:00'): 1,
         Timestamp('2020-05-16 03:15:00'): 1,
         Timestamp('2020-05-16 03:30:00'): 1,
         Timestamp('2020-05-16 03:45:00'): 1,
         Timestamp('2020-05-16 04:00:00'): 1,
         Timestamp('2020-05-16 04:15:00'): 1,
         Timestamp('2020-05-16 04:30:00'): 1,
         Timestamp('2020-05-16 04:45:00'): 1,
         Timestamp('2020-05-16 05:00:00'): 1,
         Timestamp('2020-05-16 05:15:00'): 1,
         Timestamp('2020-05-16 05:30:00'): 1,
         Timestamp('2020-05-16 05:45:00'): 1,
         Timestamp('2020-05-16 06:00:00'): 1,
         Timestamp('2020-05-16 06:15:00'): 1,
         Timestamp('2020-05-16 06:30:00'): 1,
         Timestamp('2020-05-16 06:45:00'): 1,
         Timestamp('2020-05-16 07:00:00'): 1,
         Timestamp('2020-05-16 07:15:00'): 1,
         Timestamp('2020-05-16 07:30:00'): 1,
         Timestamp('2020-05-16 07:45:00'): 1,
         Timestamp('2020-05-16 08:00:00'): 1,
         Timestamp('2020-05-16 08:15:00'): 1,
         Timestamp('2020-05-16 08:30:00'): 1,
         Timestamp('2020-05-16 08:45:00'): 1,
         Timestamp('2020-05-16 09:00:00'): 1,
         Timestamp('2020-05-16 09:15:00'): 1,
         Timestamp('2020-05-16 09:30:00'): 1,
         Timestamp('2020-05-16 09:45:00'): 1,
         Timestamp('2020-05-16 10:00:00'): 1,
         Timestamp('2020-05-16 10:15:00'): 1,
         Timestamp('2020-05-16 10:30:00'): 1,
         Timestamp('2020-05-16 10:45:00'): 1,
         Timestamp('2020-05-16 11:00:00'): 1,
         Timestamp('2020-05-16 11:15:00'): 1,
         Timestamp('2020-05-16 11:30:00'): 1,
         Timestamp('2020-05-16 11:45:00'): 1,
         Timestamp('2020-05-16 12:00:00'): 1,
         Timestamp('2020-05-16 12:15:00'): 1,
         Timestamp('2020-05-16 12:30:00'): 1,
         Timestamp('2020-05-16 12:45:00'): 1,
         Timestamp('2020-05-16 13:00:00'): 1,
         Timestamp('2020-05-16 13:15:00'): 1,
         Timestamp('2020-05-16 13:30:00'): 1,
         Timestamp('2020-05-16 13:45:00'): 1,
         Timestamp('2020-05-16 14:00:00'): 1,
         Timestamp('2020-05-16 14:15:00'): 1,
         Timestamp('2020-05-16 14:30:00'): 1,
         Timestamp('2020-05-16 14:45:00'): 1,
         Timestamp('2020-05-16 15:00:00'): 1,
         Timestamp('2020-05-16 15:15:00'): 1,
         Timestamp('2020-05-16 15:30:00'): 1,
         Timestamp('2020-05-16 15:45:00'): 1,
         Timestamp('2020-05-16 16:00:00'): 1,
         Timestamp('2020-05-16 16:15:00'): 1,
         Timestamp('2020-05-16 16:30:00'): 1,
         Timestamp('2020-05-16 16:45:00'): 1,
         Timestamp('2020-05-16 17:00:00'): 1,
         Timestamp('2020-05-16 17:15:00'): 1,
         Timestamp('2020-05-16 17:30:00'): 1,
         Timestamp('2020-05-16 17:45:00'): 1,
         Timestamp('2020-05-16 18:00:00'): 1,
         Timestamp('2020-05-16 18:15:00'): 1,
         Timestamp('2020-05-16 18:30:00'): 1,
         Timestamp('2020-05-16 18:45:00'): 1,
         Timestamp('2020-05-16 19:00:00'): 1,
         Timestamp('2020-05-16 19:15:00'): 1,
         Timestamp('2020-05-16 19:30:00'): 1,
         Timestamp('2020-05-16 19:45:00'): 1,
         Timestamp('2020-05-16 20:00:00'): 1,
         Timestamp('2020-05-16 20:15:00'): 1,
         Timestamp('2020-05-16 20:30:00'): 1,
         Timestamp('2020-05-16 20:45:00'): 1,
         Timestamp('2020-05-16 21:00:00'): 1,
         Timestamp('2020-05-16 21:15:00'): 1,
         Timestamp('2020-05-16 21:30:00'): 1,
         Timestamp('2020-05-16 21:45:00'): 1,
         Timestamp('2020-05-16 22:00:00'): 1,
         Timestamp('2020-05-16 22:15:00'): 1,
         Timestamp('2020-05-16 22:30:00'): 1,
         Timestamp('2020-05-16 22:45:00'): 1,
         Timestamp('2020-05-16 23:00:00'): 1,
         Timestamp('2020-05-16 23:15:00'): 1,
         Timestamp('2020-05-16 23:30:00'): 1,
         Timestamp('2020-05-16 23:45:00'): 1,
         Timestamp('2020-05-17 00:00:00'): 1,
         Timestamp('2020-05-17 00:15:00'): 1,
         Timestamp('2020-05-17 00:30:00'): 1,
         Timestamp('2020-05-17 00:45:00'): 1,
         Timestamp('2020-05-17 01:00:00'): 1,
         Timestamp('2020-05-17 01:15:00'): 1,
         Timestamp('2020-05-17 01:30:00'): 1,
         Timestamp('2020-05-17 01:45:00'): 1,
         Timestamp('2020-05-17 02:00:00'): 1,
         Timestamp('2020-05-17 02:15:00'): 1,
         Timestamp('2020-05-17 02:30:00'): 1,
         Timestamp('2020-05-17 02:45:00'): 1,
         Timestamp('2020-05-17 03:00:00'): 1,
         Timestamp('2020-05-17 03:15:00'): 1,
         Timestamp('2020-05-17 03:30:00'): 1,
         Timestamp('2020-05-17 03:45:00'): 1,
         Timestamp('2020-05-17 04:00:00'): 1,
         Timestamp('2020-05-17 04:15:00'): 1,
         Timestamp('2020-05-17 04:30:00'): 1,
         Timestamp('2020-05-17 04:45:00'): 1,
         Timestamp('2020-05-17 05:00:00'): 1,
         Timestamp('2020-05-17 05:15:00'): 1,
         Timestamp('2020-05-17 05:30:00'): 1,
         Timestamp('2020-05-17 05:45:00'): 1,
         Timestamp('2020-05-17 06:00:00'): 1,
         Timestamp('2020-05-17 06:15:00'): 1,
         Timestamp('2020-05-17 06:30:00'): 1,
         Timestamp('2020-05-17 06:45:00'): 1,
         Timestamp('2020-05-17 07:00:00'): 1,
         Timestamp('2020-05-17 07:15:00'): 1,
         Timestamp('2020-05-17 07:30:00'): 1,
         Timestamp('2020-05-17 07:45:00'): 1,
         Timestamp('2020-05-17 08:00:00'): 1,
         Timestamp('2020-05-17 08:15:00'): 1,
         Timestamp('2020-05-17 08:30:00'): 1,
         Timestamp('2020-05-17 08:45:00'): 1,
         Timestamp('2020-05-17 09:00:00'): 1,
         Timestamp('2020-05-17 09:15:00'): 1,
         Timestamp('2020-05-17 09:30:00'): 1,
         Timestamp('2020-05-17 09:45:00'): 1,
         Timestamp('2020-05-17 10:00:00'): 1,
         Timestamp('2020-05-17 10:15:00'): 1,
         Timestamp('2020-05-17 10:30:00'): 1,
         Timestamp('2020-05-17 10:45:00'): 1,
         Timestamp('2020-05-17 11:00:00'): 1,
         Timestamp('2020-05-17 11:15:00'): 1,
         Timestamp('2020-05-17 11:30:00'): 1,
         Timestamp('2020-05-17 11:45:00'): 1,
         Timestamp('2020-05-17 12:00:00'): 1,
         Timestamp('2020-05-17 12:15:00'): 1,
         Timestamp('2020-05-17 12:30:00'): 1,
         Timestamp('2020-05-17 12:45:00'): 1,
         Timestamp('2020-05-17 13:00:00'): 1,
         Timestamp('2020-05-17 13:15:00'): 1,
         Timestamp('2020-05-17 13:30:00'): 1,
         Timestamp('2020-05-17 13:45:00'): 1,
         Timestamp('2020-05-17 14:00:00'): 1,
         Timestamp('2020-05-17 14:15:00'): 1,
         Timestamp('2020-05-17 14:30:00'): 1,
         Timestamp('2020-05-17 14:45:00'): 1,
         Timestamp('2020-05-17 15:00:00'): 1,
         Timestamp('2020-05-17 15:15:00'): 1,
         Timestamp('2020-05-17 15:30:00'): 1,
         Timestamp('2020-05-17 15:45:00'): 1,
         Timestamp('2020-05-17 16:00:00'): 1,
         Timestamp('2020-05-17 16:15:00'): 1,
         Timestamp('2020-05-17 16:30:00'): 1,
         Timestamp('2020-05-17 16:45:00'): 1,
         Timestamp('2020-05-17 17:00:00'): 1,
         Timestamp('2020-05-17 17:15:00'): 1,
         Timestamp('2020-05-17 17:30:00'): 1,
         Timestamp('2020-05-17 17:45:00'): 1,
         Timestamp('2020-05-17 18:00:00'): 1,
         Timestamp('2020-05-17 18:15:00'): 1,
         Timestamp('2020-05-17 18:30:00'): 1,
         Timestamp('2020-05-17 18:45:00'): 1,
         Timestamp('2020-05-17 19:00:00'): 1,
         Timestamp('2020-05-17 19:15:00'): 1,
         Timestamp('2020-05-17 19:30:00'): 1,
         Timestamp('2020-05-17 19:45:00'): 1,
         Timestamp('2020-05-17 20:00:00'): 1,
         Timestamp('2020-05-17 20:15:00'): 1,
         Timestamp('2020-05-17 20:30:00'): 1,
         Timestamp('2020-05-17 20:45:00'): 1,
         Timestamp('2020-05-17 21:00:00'): 1,
         Timestamp('2020-05-17 21:15:00'): 1,
         Timestamp('2020-05-17 21:30:00'): 1,
         Timestamp('2020-05-17 21:45:00'): 1,
         Timestamp('2020-05-17 22:00:00'): 1,
         Timestamp('2020-05-17 22:15:00'): 1,
         Timestamp('2020-05-17 22:30:00'): 1,
         Timestamp('2020-05-17 22:45:00'): 1,
         Timestamp('2020-05-17 23:00:00'): 1,
         Timestamp('2020-05-17 23:15:00'): 1,
         Timestamp('2020-05-17 23:30:00'): 1,
         Timestamp('2020-05-17 23:45:00'): 1,
         Timestamp('2020-05-18 00:00:00'): 1,
         Timestamp('2020-05-18 00:15:00'): 1,
         Timestamp('2020-05-18 00:30:00'): 1,
         Timestamp('2020-05-18 00:45:00'): 1,
         Timestamp('2020-05-18 01:00:00'): 1,
         Timestamp('2020-05-18 01:15:00'): 1,
         Timestamp('2020-05-18 01:30:00'): 1,
         Timestamp('2020-05-18 01:45:00'): 1,
         Timestamp('2020-05-18 02:00:00'): 1,
         Timestamp('2020-05-18 02:15:00'): 1,
         Timestamp('2020-05-18 02:30:00'): 1,
         Timestamp('2020-05-18 02:45:00'): 1,
         Timestamp('2020-05-18 03:00:00'): 1,
         Timestamp('2020-05-18 03:15:00'): 1,
         Timestamp('2020-05-18 03:30:00'): 1,
         Timestamp('2020-05-18 03:45:00'): 1,
         Timestamp('2020-05-18 04:00:00'): 1,
         Timestamp('2020-05-18 04:15:00'): 1,
         Timestamp('2020-05-18 04:30:00'): 1,
         Timestamp('2020-05-18 04:45:00'): 1,
         Timestamp('2020-05-18 05:00:00'): 1,
         Timestamp('2020-05-18 05:15:00'): 1,
         Timestamp('2020-05-18 05:30:00'): 1,
         Timestamp('2020-05-18 05:45:00'): 1,
         Timestamp('2020-05-18 06:00:00'): 1,
         Timestamp('2020-05-18 06:15:00'): 1,
         Timestamp('2020-05-18 06:30:00'): 1,
         Timestamp('2020-05-18 06:45:00'): 1,
         Timestamp('2020-05-18 07:00:00'): 1,
         Timestamp('2020-05-18 07:15:00'): 1,
         Timestamp('2020-05-18 07:30:00'): 1,
         Timestamp('2020-05-18 07:45:00'): 1,
         Timestamp('2020-05-18 08:00:00'): 1,
         Timestamp('2020-05-18 08:15:00'): 1,
         Timestamp('2020-05-18 08:30:00'): 1,
         Timestamp('2020-05-18 08:45:00'): 1,
         Timestamp('2020-05-18 09:00:00'): 1,
         Timestamp('2020-05-18 09:15:00'): 1,
         Timestamp('2020-05-18 09:30:00'): 1,
         Timestamp('2020-05-18 09:45:00'): 1,
         Timestamp('2020-05-18 10:00:00'): 1,
         Timestamp('2020-05-18 10:15:00'): 1,
         Timestamp('2020-05-18 10:30:00'): 1,
         Timestamp('2020-05-18 10:45:00'): 1,
         Timestamp('2020-05-18 11:00:00'): 1,
         Timestamp('2020-05-18 11:15:00'): 1,
         Timestamp('2020-05-18 11:30:00'): 1,
         Timestamp('2020-05-18 11:45:00'): 1,
         Timestamp('2020-05-18 12:00:00'): 1,
         Timestamp('2020-05-18 12:15:00'): 1,
         Timestamp('2020-05-18 12:30:00'): 1,
         Timestamp('2020-05-18 12:45:00'): 1,
         Timestamp('2020-05-18 13:00:00'): 1,
         Timestamp('2020-05-18 13:15:00'): 1,
         Timestamp('2020-05-18 13:30:00'): 1,
         Timestamp('2020-05-18 13:45:00'): 1,
         Timestamp('2020-05-18 14:00:00'): 1,
         Timestamp('2020-05-18 14:15:00'): 1,
         Timestamp('2020-05-18 14:30:00'): 1,
         Timestamp('2020-05-18 14:45:00'): 1,
         Timestamp('2020-05-18 15:00:00'): 1,
         Timestamp('2020-05-18 15:15:00'): 1,
         Timestamp('2020-05-18 15:30:00'): 1,
         Timestamp('2020-05-18 15:45:00'): 1,
         Timestamp('2020-05-18 16:00:00'): 1,
         Timestamp('2020-05-18 16:15:00'): 1,
         Timestamp('2020-05-18 16:30:00'): 1,
         Timestamp('2020-05-18 16:45:00'): 1,
         Timestamp('2020-05-18 17:00:00'): 1,
         Timestamp('2020-05-18 17:15:00'): 1,
         Timestamp('2020-05-18 17:30:00'): 1,
         Timestamp('2020-05-18 17:45:00'): 1,
         Timestamp('2020-05-18 18:00:00'): 1,
         Timestamp('2020-05-18 18:15:00'): 1,
         Timestamp('2020-05-18 18:30:00'): 1,
         Timestamp('2020-05-18 18:45:00'): 1,
         Timestamp('2020-05-18 19:00:00'): 1,
         Timestamp('2020-05-18 19:15:00'): 1,
         Timestamp('2020-05-18 19:30:00'): 1,
         Timestamp('2020-05-18 19:45:00'): 1,
         Timestamp('2020-05-18 20:00:00'): 1,
         Timestamp('2020-05-18 20:15:00'): 1,
         Timestamp('2020-05-18 20:30:00'): 1,
         Timestamp('2020-05-18 20:45:00'): 1,
         Timestamp('2020-05-18 21:00:00'): 1,
         Timestamp('2020-05-18 21:15:00'): 1,
         Timestamp('2020-05-18 21:30:00'): 1,
         Timestamp('2020-05-18 21:45:00'): 1,
         Timestamp('2020-05-18 22:00:00'): 1,
         Timestamp('2020-05-18 22:15:00'): 1,
         Timestamp('2020-05-18 22:30:00'): 1,
         Timestamp('2020-05-18 22:45:00'): 1,
         Timestamp('2020-05-18 23:00:00'): 1,
         Timestamp('2020-05-18 23:15:00'): 1,
         Timestamp('2020-05-18 23:30:00'): 1,
         Timestamp('2020-05-18 23:45:00'): 1,
         Timestamp('2020-05-19 00:00:00'): 1,
         Timestamp('2020-05-19 00:15:00'): 1,
         Timestamp('2020-05-19 00:30:00'): 1,
         Timestamp('2020-05-19 00:45:00'): 1,
         Timestamp('2020-05-19 01:00:00'): 1,
         Timestamp('2020-05-19 01:15:00'): 1,
         Timestamp('2020-05-19 01:30:00'): 1,
         Timestamp('2020-05-19 01:45:00'): 1,
         Timestamp('2020-05-19 02:00:00'): 1,
         Timestamp('2020-05-19 02:15:00'): 1,
         Timestamp('2020-05-19 02:30:00'): 1,
         Timestamp('2020-05-19 02:45:00'): 1,
         Timestamp('2020-05-19 03:00:00'): 1,
         Timestamp('2020-05-19 03:15:00'): 1,
         Timestamp('2020-05-19 03:30:00'): 1,
         Timestamp('2020-05-19 03:45:00'): 1,
         Timestamp('2020-05-19 04:00:00'): 1,
         Timestamp('2020-05-19 04:15:00'): 1,
         Timestamp('2020-05-19 04:30:00'): 1,
         Timestamp('2020-05-19 04:45:00'): 1,
         Timestamp('2020-05-19 05:00:00'): 1,
         Timestamp('2020-05-19 05:15:00'): 1,
         Timestamp('2020-05-19 05:30:00'): 1,
         Timestamp('2020-05-19 05:45:00'): 1,
         Timestamp('2020-05-19 06:00:00'): 1,
         Timestamp('2020-05-19 06:15:00'): 1,
         Timestamp('2020-05-19 06:30:00'): 1,
         Timestamp('2020-05-19 06:45:00'): 1,
         Timestamp('2020-05-19 07:00:00'): 1,
         Timestamp('2020-05-19 07:15:00'): 1,
         Timestamp('2020-05-19 07:30:00'): 1,
         Timestamp('2020-05-19 07:45:00'): 1,
         Timestamp('2020-05-19 08:00:00'): 1,
         Timestamp('2020-05-19 08:15:00'): 1,
         Timestamp('2020-05-19 08:30:00'): 1,
         Timestamp('2020-05-19 08:45:00'): 1,
         Timestamp('2020-05-19 09:00:00'): 1,
         Timestamp('2020-05-19 09:15:00'): 1,
         Timestamp('2020-05-19 09:30:00'): 1,
         Timestamp('2020-05-19 09:45:00'): 1,
         Timestamp('2020-05-19 10:00:00'): 1,
         Timestamp('2020-05-19 10:15:00'): 1,
         Timestamp('2020-05-19 10:30:00'): 1,
         Timestamp('2020-05-19 10:45:00'): 1,
         Timestamp('2020-05-19 11:00:00'): 1,
         Timestamp('2020-05-19 11:15:00'): 1,
         Timestamp('2020-05-19 11:30:00'): 1,
         Timestamp('2020-05-19 12:30:00'): 1,
         Timestamp('2020-05-19 12:45:00'): 1,
         Timestamp('2020-05-19 13:00:00'): 1,
         Timestamp('2020-05-19 13:15:00'): 1,
         Timestamp('2020-05-19 13:30:00'): 1,
         Timestamp('2020-05-19 13:45:00'): 1,
         Timestamp('2020-05-19 14:00:00'): 1,
         Timestamp('2020-05-19 14:15:00'): 1,
         Timestamp('2020-05-19 14:30:00'): 1,
         Timestamp('2020-05-19 14:45:00'): 1,
         Timestamp('2020-05-19 15:00:00'): 1,
         Timestamp('2020-05-19 15:15:00'): 1,
         Timestamp('2020-05-19 15:30:00'): 1,
         Timestamp('2020-05-19 15:45:00'): 1,

In [12]:
df.isnull().values.any()

False

In [22]:
import numpy as np
df3 = pd.concat([df, df2], axis=1)

df3.ffill(axis = 0, inplace=True)

#n = 0
#loc=0
#df3.fillna(0)

#for p in df3['AMBIENT_TEMPERATURE']:
#    df3[loc]['AMBIENT_TEMPERATURE'] 
#    if p == 0:            
#        df.set_value(loc, 'AMBIENT_TEMPERATURE',df3.get_value(loc - 1,'AMBIENT_TEMPERATURE'))
#    loc = loc+1

df3.drop(['DATE_TIME','PLANT_ID','SOURCE_KEY','DC_POWER','AC_POWER','TOTAL_YIELD','Datetime'], axis=1,inplace=True)
df3 = df3[['AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION', 'DAILY_YIELD']]
df3

       AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION  DAILY_YIELD
0                25.184316           22.857507          0.0        0.000
1                25.084589           22.761668          0.0        0.000
2                24.935753           22.592306          0.0        0.000
3                24.846130           22.360852          0.0        0.000
4                24.621525           22.165423          0.0        0.000
...                    ...                 ...          ...          ...
68773            21.909288           20.427972          0.0     5967.000
68774            21.909288           20.427972          0.0     5147.625
68775            21.909288           20.427972          0.0     5819.000
68776            21.909288           20.427972          0.0     5817.000
68777            21.909288           20.427972          0.0     5910.000

[68778 rows x 4 columns]

In [31]:
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
#in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#in_seq1 = df2['AMBIENT_TEMPERATURE'].to_numpy()
#in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
#in_seq2 = df2['MODULE_TEMPERATURE'].to_numpy()
#in_seq3 = df2['IRRADIATION'].to_numpy()
#out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

#out_seq = df.map(lambda x: x['Datetime']== df2['Datetime'] ) to_numpy()
#out_seq = out_df['Datetime'].to_numpy()
# convert to [rows, columns] structure
#in_seq1 = in_seq1.reshape((len(in_seq1), 1))
#in_seq2 = in_seq2.reshape((len(in_seq2), 1))
#out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
#dataset = hstack((in_seq1, in_seq2, out_seq))
dataset = df3.to_numpy()

# choose a number of time steps
n_steps = 4
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(y)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
print(type(X))
print(n_features)
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([[23, 33, 22, 0.22], [20, 22, 21, 0.13], [35, 40, 30, 1.3]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[   0.    0.    0. ... 5819. 5817. 5910.]
<class 'numpy.ndarray'>
3
[[2.7374842]]

In [32]:
x_input = array([[23, 33, 0.22, 4544], [20, 22, 0.13, 3778], [35, 40, 1.3, 6678]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[7822.8765]]